travis:
  secure:
    BINSTAR_TOKEN: u3beudrKbkTQO9Zofykl6kcPpcHaQOLd5JjasGsf43Qp0qvjMHTfbOMjbOPXsjCxtn57mGA9Fn8A/zajNCLm3Roc2Ar8VByO9h6S9e3FJoqp90qN2IvklBm+s7aGZwVE0WcSBD9G0Zts1Maiq4T/SXDy68rUj1ydMgJuzOYbbhQ3+Z5cl9SEe4TwjsfT2XQrN8ARRhr+GMKwzYBVI6Evyl4mbXgowczOrTloTh6GT8ixVtsy5WRoIqTF0kUUDiT/vs4ZGRkEvg/tLj6XcHfLEM90EE+sHa2nRbaAMZrb1x36za7Ka8D5js/W8pAyyMDuYeZQ8IilW1AbWF1DXwQiuX0OXoKzN/bhXz4akc6YHVB8xZrycwz5phZSnQ+hibm+Yie2ReYsj0VwabikB7N6tpFBhiqINMRcRtUYaA8P/ffJsnmojjk8qVIF8j2YNUVKIikSfy9bvrd2IAT23EODFmZMCqKNIKcd9hSrv7TEMMNPxsywvZDgBp+NQm5SgtbhOJbImKKCPCAf0za4vHMDs5H99e9SrNv3FPfJ6Q3AG2BuCCPRowfLq8qotijAr+RKECyoxKjDqBevL4p6MHOKN7ESgITu4rwxnIgJ9tWsJwxb4sGq6NQwBudosKxe0UmdswvDOHpby3tCoRzy0X569VX7lWuk5rhTQXbD17IIWUs=
bot:
  automerge: true
conda_forge_output_validation: false
